#!/usr/bin/env python3
"""
secure_apply.py

Enforces cryptographic provenance verification for Terraform
Infrastructure-as-Code before allowing deployment.

This script verifies a Sigstore DSSE attestation generated by cosign
and ensures that the Terraform configuration has not been modified
since it was attested. Terraform execution is blocked on verification
failure.
"""

import subprocess
import sys


def run_command(command: str, error_message: str) -> None:
    """
    Execute a shell command and terminate execution on failure.

    :param command: Command to execute
    :param error_message: Error message to display on failure
    """
    print(f"[INFO] Executing: {command}")
    result = subprocess.run(command, shell=True)

    if result.returncode != 0:
        print(f"[ERROR] {error_message}")
        sys.exit(1)


def verify_attestation(terraform_file: str) -> None:
    """
    Verify the DSSE provenance attestation for the given Terraform file.

    This verification ensures:
    - Integrity of the Terraform configuration
    - Authenticity of the signer
    - Correct binding between artifact and provenance metadata
    """
    command = (
        f"cosign verify-blob-attestation "
        f"--key cosign.pub "
        f"--bundle {terraform_file}.attestation.sigstore.json "
        f"{terraform_file}"
    )
    run_command(command, "Provenance attestation verification failed.")


def terraform_apply() -> None:
    """
    Execute terraform apply after successful verification.
    """
    run_command(
        "terraform apply -auto-approve",
        "Terraform apply failed."
    )


def main() -> None:
    """
    Main enforcement workflow.
    """
    terraform_file = "main.tf"

    print("Starting secure Terraform enforcement.")

    verify_attestation(terraform_file)

    print("Verification successful. Proceeding with Terraform apply.")

    terraform_apply()


if __name__ == "__main__":
    main()

